name: mif_app
description: Modern Islamic Foundation cross platform client
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  web: ^1.1.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^11.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mif-logo.png
    - assets/learning-hero.png
  fonts:
    - family: NotoSansDisplay
      fonts:
        - asset: assets/fonts/NotoSansDisplay-Regular.ttf
        - asset: assets/fonts/NotoSansDisplay-Bold.ttf
          weight: 700
    - family: NotoSerifDisplay
      fonts:
        - asset: assets/fonts/NotoSerifDisplay-Regular.ttf
        - asset: assets/fonts/NotoSerifDisplay-Bold.ttf
          weight: 700
