import { Router } from "express";

import { announcementsRouter } from "../modules/announcements/announcements.routes";
import { attendanceRouter } from "../modules/attendance/attendance.routes";
import { authRouter } from "../modules/auth/auth.routes";
import { classesRouter, enrollmentsRouter } from "../modules/classes/classes.routes";
import { expensesRouter, feeStructuresRouter, invoicesRouter } from "../modules/finance/finance.routes";
import { hifdhRouter } from "../modules/hifdh/hifdh.routes";
import { learnerRouter } from "../modules/learner/learner.routes";
import { coursesRouter, subjectsRouter, teachingCoursesRouter } from "../modules/learning/learning.routes";
import { organizationsRouter } from "../modules/organizations/organizations.routes";
import { parentPortalRouter } from "../modules/parent-portal/parent-portal.routes";
import { paymentsRouter, webhooksRouter } from "../modules/payments/payments.routes";
import { publicInquiriesRouter } from "../modules/public-inquiries/public-inquiries.routes";
import { reportsRouter } from "../modules/reports/reports.routes";
import { guardiansRouter, studentsRouter } from "../modules/students/students.routes";
import { usersRouter } from "../modules/users/users.routes";
import { healthRouter } from "./health.route";
import { publicRouter } from "./public.route";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/public", publicRouter);
apiRouter.use("/announcements", announcementsRouter);
apiRouter.use("/attendance", attendanceRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/organizations", organizationsRouter);
apiRouter.use("/learner", learnerRouter);
apiRouter.use("/subjects", subjectsRouter);
apiRouter.use("/courses", coursesRouter);
apiRouter.use("/teaching/courses", teachingCoursesRouter);
apiRouter.use("/hifdh-progress", hifdhRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/parent-portal", parentPortalRouter);
apiRouter.use("/public-inquiries", publicInquiriesRouter);
apiRouter.use("/students", studentsRouter);
apiRouter.use("/guardians", guardiansRouter);
apiRouter.use("/classes", classesRouter);
apiRouter.use("/enrollments", enrollmentsRouter);
apiRouter.use("/fee-structures", feeStructuresRouter);
apiRouter.use("/invoices", invoicesRouter);
apiRouter.use("/expenses", expensesRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/webhooks", webhooksRouter);
